### ISSUE TITLE
FS Changes are not tracked

### ISSUE THREAD

**Issue by delphir-com** [0leksandr/sshmirror#2]
For some reason my fs changes are not tracked by sshmirror tool. 

once the connection is established and "done" message was written - nothing else happens anymore.

Running the tool with strace shows an output like this every time when I save changes into the file (so the the FS changes seems to be noticed, but it just don't proceed with them)

```
) = 0
futex(0x5f5bd0, FUTEX_WAIT_PRIVATE, 0, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0xc000200550, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5f5bd0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x5f5bd0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x5f5bd0, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x5f5bd0, FUTEX_WAIT_PRIVATE, 0, NULL

```

Ubuntu 20.04

Linux KUBUNTU 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 0leksandr** [comment]
@delphir-com,  thank you for the report, and the tip!
The param should not be a must indeed (it was not meant to be).
Fixed now, and published in release 1.4
