### ISSUE TITLE
my.go is missing

### ISSUE THREAD

**Issue by delphir-com** [0leksandr/sshmirror#3]
the current master do not contain the my.go file which is linked through a symlink in the latest commit

```
linux/amd64
can't load package: package github.com/0leksandr/sshmirror: open /media/k/SSD2/ApacheServer/web/2021/mobymax/sshmirror/my.go: no such file or directory
Build failed for linux/amd64
```

building the version before this my.go change - works just fine

**Comment by 0leksandr** [comment]
Hi! Thank you for the report, and sorry for the late reply.
It should be fixed now in release 1.4
